import Head from 'next/head'
import { strict as assert } from 'assert'

export default function Home({ githubAuthUrl }) {
    return (
        <>

            <Head>
                <title>punci.io</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <a href={ githubAuthUrl }>Login</a>
            </main>

        </>
    )
}

export async function getStaticProps() {
    const GITHUB_AUTH_URL = process.env.GITHUB_AUTH_URL
    assert(GITHUB_AUTH_URL.length  && GITHUB_AUTH_URL.length > 1)
    return {
        props: {
            githubAuthUrl: GITHUB_AUTH_URL
        }
    }
}
