import Head from 'next/head'
import React from 'react'
import { strict as assert } from 'assert'

export default class Home extends React.Component {

    constructor(props) {
        super(props)
        this.state = {
            user: null
        }
    }

    async componentDidMount() {
        const res = await fetch('api/v1/user/me')
        const { user } = await res.json()
        this.setState({ user })
    }

    login() {
        return <a href='/auth/github'>Login with GitHub</a>
    }

    content(user) {
        return <>
            <p>
                {user.info.login}
            </p>
            <p>
                <img src={user.info.avatar_url} width='40' height='40' />
            </p>
            <form action='/auth/logout' method='POST'>
                <input type='submit' value='Logout' />
            </form>
        </>
    }

    render() {
        return (
            <>

                <Head>
                    <title>punci.io</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main>
                    {this.state.user ? this.content(this.state.user) : this.login()}
                </main>

            </>
        )
    }
}
